### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by pulkomandy** [pulkomandy/Sawteeth#38]
Before a release:
- [ ] Check if we can compile with gcc2 and gcc8 (32 + 64bit) without warnings, both the editor and STLib
- [ ] Update readme.html, version.history, Resource.rdef which each contain at least the version number
- [ ] The "default song" title also needs to be changed as it contains the version number
